# version: '3.4'

volumes:
  postgres-data:
    name: face_recognition_db_postgres-data 

services:
  ab-postgres-db:
    restart: always
    container_name: "ab-postgres-db"
    build:
      context: ./db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_DB=${postgres_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data