version: "3.8"
services:
  gpu-app:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    ports:
      - "5001:5001"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - .:/app
    restart: always
